'good'		 'good file system'
'badinode'	 'file system with a bad type in an inode'
'badaddr'	 'file system with a bad direct address in an inode'
'badindir1'	 'file system with a bad indirect address in an inode'
'badindir2'	 'file system with a bad indirect address in an inode'
'badroot'	 'file system with a root directory in bad location'
'badroot2'	 'file system with a bad root directory in good location'
'badfmt'	 'file system without . or .. directories'
'mrkfree'	 'file system with an inuse direct block marked free'
'indirfree'	 'file system with an inuse indirect block marked free'
'mrkused'	 'file system with a free block marked used'
'addronce'	 'file system with a direct address used more than once'
'addronce2'	 'file system with an indirect address used more than once'
'imrkused'	 'file system with inode marked used, but not referenced in a directory'
'imrkfree'	 'file system with inode marked free, but referenced in a directory'
'badrefcnt2'	 'file system which has an inode that is referenced more than its reference count'
'goodlarge'	 'large good file system'
'goodrefcnt'	  'file system with only good file reference counts'
'goodlink'	  'file system with only good directory link counts'
'goodrm'	  'good file system having some files removed'
'dironce'	  'file system with a directory appearing more than once'
'badlarge'	  'large file system with an indirect directory appearing more than once'
